### ISSUE TITLE
Motion Planning TODO

### ISSUE THREAD

**Issue by GreatAlexander** [edinferno/edinferno#83]
- ~~Generate and load stand up motion~~ <- Not Needed for now
- [x] Generate and load kick motion
- [x] Create and implement stand up state
- [x] Create and implement sit down state
- [x] Generate and load chirp (very fast) kick
- [x] Convert kicks into actions so they may be called by agent
- [ ] Use absolute coordinate frame for end effector control (Needs testing)
- [ ] Use arm balancing for better stability (Works but needs tuning and implementation)
